service: trabalho20

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  tracing:
      apiGateway: true
      lambda: true

  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:ChangeMessageVisibility
        - sqs:DeleteMessage
        - sqs:ReceiveMessage
        - sqs:SendMessage
        - sqs:GetQueueAttributes
      Resource: "arn:aws:sqs:us-east-1:*:terraform-example-queue_dev"

package:
  exclude:
    - layer/**

layers:
  LayersDependecies:
    path: layer
    description: "lambda dependencies"

functions:
  lambda20:
    handler: print.lambda_handler
    events:
      - sqs: <INSIRA O ARN DA FILA SQS PRINCIPAL>
    layers:
      - {Ref: LayersDependeciesLambdaLayer}
