service: trabalho10

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  tracing:
      apiGateway: true
      lambda: true

  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:ChangeMessageVisibility
        - sqs:DeleteMessage
        - sqs:ReceiveMessage
        - sqs:SendMessage
        - sqs:GetQueueAttributes
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvent
        - xray:*
      Resource: "arn:aws:sqs:us-east-1:*:terraform-example-queue*"

package:
  exclude:
    - layer/**

layers:
  LayersDependecies:
    path: layer
    description: "lambda dependencies"
    
functions:
  lambda10:
    handler: send.lambda_handler
    events:
      - http:
          path: inseresqs
          method: post
    layers:
      - {Ref: LayersDependeciesLambdaLayer}
