service: trabalho30

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  tracing:
      apiGateway: true
      lambda: true

  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:ChangeMessageVisibility
        - sqs:DeleteMessage
        - sqs:ReceiveMessage
        - sqs:SendMessage
        - sqs:GetQueueAttributes
        - sns:Publish
      Resource: "arn:aws:sns:us-east-1:*:terraform-updates-topic*"

package:
  exclude:
    - layer/**

layers:
  LayersDependecies:
    path: layer
    description: "lambda dependencies"

functions:
  lambda30:
    handler: send_to_topic.lambda_handler
    events:
      - sqs: <INSIRA O ARN DA FILA SQS SECUNDARIA DLQ>
    layers:
      - {Ref: LayersDependeciesLambdaLayer}
